version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: ${APP_NAME}-nginx
    ports:
      - "${APP_WEB_PORT}:80"
    image: atrem2023/k8s-basics:amd64
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - php

  php:
    build:
      args:
        user: ${DOCKER_USER}
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    image: atrem2023/otus-docker:amd64
    volumes:
      - ./:${APP_PATH}
    depends_on:
      - db
    container_name: ${APP_NAME}_php

  db:
    image: postgres
    container_name: ${APP_NAME}_db
    volumes:
      - ./tmp/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'