apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-php
  namespace: k8s-basics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-php
  template:
    metadata:
      labels:
        app: laravel-php
    spec:
      containers:
        - name: php
          image: atrem2023/app-php:amd64
          ports:
            - containerPort: 9000
          env:
            - name: DB_CONNECTION
              value: pgsql
            - name: DB_HOST
              value: postgres-service
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: k8s_basics
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: POSTGRES_PASSWORD
